language: python
python: "2.7"

install:
        - pip install coverage pytest pytest-pylint
scripts:
        - pytest --pylint src/*.py
        - coverage run -m pytest src/*.py 
        - coverage report -m src/*.py



